spring.application.name=Url_shortener
spring.datasource.url=jdbc:postgresql://localhost:5432/url_shortner
spring.datasource.username=your_username
spring.datasource.password=your_password

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
